<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Default Namespace Paths
    |--------------------------------------------------------------------------
    |
    | Configure where each type of file should be generated.
    |
    */
    'namespaces' => [
        'model' => 'App\\Models',
        'controller' => 'App\\Http\\Controllers',
        'service' => 'App\\Services',
        'repository' => 'App\\Repositories',
        'resource' => 'App\\Http\\Resources',
        'request' => 'App\\Http\\Requests',
        'policy' => 'App\\Policies',
    ],

    /*
    |--------------------------------------------------------------------------
    | Default Paths
    |--------------------------------------------------------------------------
    |
    | Configure the file paths for each type.
    |
    */
    'paths' => [
        'model' => 'app/Models',
        'controller' => 'app/Http/Controllers',
        'service' => 'app/Services',
        'repository' => 'app/Repositories',
        'resource' => 'app/Http/Resources',
        'request' => 'app/Http/Requests',
        'policy' => 'app/Policies',
        'migration' => 'database/migrations',
        'factory' => 'database/factories',
        'seeder' => 'database/seeders',
    ],

    /*
    |--------------------------------------------------------------------------
    | Files to Generate
    |--------------------------------------------------------------------------
    |
    | Which files should be generated by default.
    | Can be overridden with command options.
    |
    */
    'generate' => [
        'model' => true,
        'controller' => true,
        'service' => true,
        'repository' => true,
        'resource' => true,
        'store_request' => true,
        'update_request' => true,
        'policy' => true,
        'migration' => true,
        'factory' => true,
        'seeder' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Use Repository Pattern
    |--------------------------------------------------------------------------
    |
    | If true, Controller uses Service, Service uses Repository.
    | If false, Controller uses Service, Service uses Model directly.
    |
    */
    'use_repository' => true,

    /*
    |--------------------------------------------------------------------------
    | API Controller
    |--------------------------------------------------------------------------
    |
    | Generate API-style controller (returns JSON) instead of web controller.
    |
    */
    'api_controller' => true,

    /*
    |--------------------------------------------------------------------------
    | Default Pagination
    |--------------------------------------------------------------------------
    |
    | Default pagination limit for index/search methods.
    |
    */
    'default_pagination' => 15,

    /*
    |--------------------------------------------------------------------------
    | Add Routes
    |--------------------------------------------------------------------------
    |
    | Automatically add routes to api.php or web.php file.
    |
    */
    'add_routes' => true,
    'routes_file' => 'api', // 'api' or 'web'

    /*
    |--------------------------------------------------------------------------
    | Soft Deletes
    |--------------------------------------------------------------------------
    |
    | Include soft deletes in model by default.
    |
    */
    'soft_deletes' => false,

    /*
    |--------------------------------------------------------------------------
    | Timestamps
    |--------------------------------------------------------------------------
    |
    | Include timestamps in migration by default.
    |
    */
    'timestamps' => true,

    /*
    |--------------------------------------------------------------------------
    | UUID Primary Key
    |--------------------------------------------------------------------------
    |
    | Use UUID instead of auto-incrementing ID.
    |
    */
    'uuid' => false,
];
